version: "3"

services:
  postgres:
    image: postgres:10.2
    environment:
      POSTGRES_PASSWORD: 'ljflejffjhi3984n'
      POSTGRES_USER: 'user'
      POSTGRES_DB: 'password'
    ports:
      - "5432:5432"
    #    volumes:
    #      - 'postgres:/var/lib/postgresql/data'
    labels:
      - 'traefik.docker.network=laravel'
      - 'traefik.backend=postgres'
      - 'traefik.port=3306'
      - 'traefik.frontend.rule=Host:postgres.docker.localhost'

  php:
    image: wodby/php:8-4.18.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_BLACKFIRE: 1
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/php-nginx:1.15-4.2.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public
    user: 1000:82
    volumes:
      - ./:/var/www/html
    labels:
      - 'traefik.docker.network=laravel'
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:laravel.docker.localhost'

  traefik:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=laravel"

volumes:
  codebase:
